import { EventTarget } from "./EventTarget";
import type { DOMString } from "./WebIDL.types";

/**
 * The `Event` interface represents an event which takes place on an
 * {@linkcode EventTarget}.
 * 
 * An event can be triggered by the user action e.g., clicking the mouse button
 * or tapping keyboard, or generated by APIs to represent the progress of an
 * asynchronous task. It can also be triggered programmatically, such as by
 * calling the {@linkcode HTMLElement.click()} method of an element, or by
 * defining the event, then sending it to a specified target using
 * {@linkcode EventTarget.dispatchEvent()}. 
 * 
 * There are many types of events, some of which use other interfaces based on
 * the main `Event` interface. `Event` itself contains the properties and methods
 * which are common to all events.
 * 
 * Many DOM elements can be set up to accept (or "listen" for) these events, and
 * execute code in response to process (or "handle") them. Event-handlers are
 * usually connected (or "attached") to various
 * {@link https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements HTML elements}
 * (such as `<button>`, `<div>`, `<span>`, etc.) using
 * {@linkcode EventTarget.addEventListener()},
 * and this generally replaces using the old HTML
 * {@link https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes event handler attributes}.
 * Further, when properly added, such handlers can also be disconnected if needed
 * using {@linkcode EventTarget.removeEventListener()|removeEventListener()}.
 * 
 * > Note: One element can have several such handlers, even for the exact same
 * event—particularly if separate, independent code modules attach them, each
 * for its own independent purposes. (For example, a webpage with an
 * advertising-module and statistics-module both monitoring video-watching.)
 * 
 * When there are many nested elements, each with its own handler(s), event
 * processing can become very complicated—especially where a parent element
 * receives the very same event as its child elements because "spatially" they
 * overlap so the event technically occurs in both, and the processing order of
 * such events depends on the
 * {@link https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Scripting/Event_bubbling Event bubbling}
 * settings of each handler triggered.
 * 
 * https://developer.mozilla.org/en-US/docs/Web/API/Event
 */
interface Event {
  /**
   * A boolean value indicating whether or not the event bubbles up through the DOM.
   */
  readonly bubbles: boolean;
  /**
   * A boolean value indicating whether the event is cancelable.
   */
  readonly cancelable: boolean;
  /**
   * A boolean indicating whether or not the event can bubble across the boundary
   * between the shadow DOM and the regular DOM.
   */
  readonly composed: boolean;
  /**
   * A reference to the currently registered target for the event. This is the
   * object to which the event is currently slated to be sent. It's possible this
   * has been changed along the way through *retargeting*.
   */
  readonly currentTarget?: EventTarget;
  /**
   * Indicates whether or not the call to
   * {@linkcode Event.preventDefault()|event.preventDefault()} canceled the event.
   */
  readonly defaultPrevented: boolean;
  /**
   * Indicates which phase of the event flow is being processed. It is one of
   * the following numbers: `NONE`, `CAPTURING_PHASE`, `AT_TARGET`, `BUBBLING_PHASE`.
   */
  readonly eventPhase: number;
  /**
   * Indicates whether or not the event was initiated by the browser (after a
   * user click, for instance) or by a script (using an event creation method,
   * for example).
   */
  readonly isTrusted: boolean;
  /**
   * A reference to the object to which the even was original dispatched.
   */
  readonly target?: EventTarget;
  /**
   * The time at which the event was created (in milliseconds). By specification,
   * this value is time since epoch—but in reality, browsers' definitions vary.
   * In addition, work is underway to change this to be a
   * {@linkcode https://developer.mozilla.org/en-US/docs/Web/API/DOMHighResTimeStamp DOMHighResTimeStamp}
   * instead.
   */
  readonly timeStamp: number;
  /**
   * The name identifying the type of the event.
   */
  readonly type: DOMString;

  /**
   * Returns the event's path (an array of objects on which listeners will be
   * invoked). This does not include nodes in shadow trees if the shadow root
   * was created with its {@linkcode ShadowRoot.mode} closed.
   */
  composedPath(): EventTarget[];
  /**
   * Cancels the event (if it is cancelable).
   */
  preventDefault(): void;
  /**
   * For this particular event, prevent all other listeners from being called.
   * This includes listeners attached to the same element as well as those
   * attached to elements that will be traversed later (during the capture
   * phase, for instance).
   */
  stopImmediatePropagation(): void;
  /**
   * Stops the propagation of events further along in the DOM.
   */
  stopPropagation(): void;
}

interface EventConstructor {
  new(type: DOMString, options?: EventInit): Event;
}

enum EventPhase {
  NONE = 0,
  CAPTURING_PHASE = 1,
  AT_TARGET = 2,
  BUBBLING_PHASE = 3,
}

export class EventImpl implements Event {
  constructor(type: DOMString, options?: EventInit) {
    this.#type = type;
    this.#bubbles = options?.bubbles || false;
    this.#cancelable = options?.cancelable || false;
    this.#composed = options?.composed || false;
  }

  #bubbles: boolean;
  #cancelable: boolean;
  #composed: boolean;
  #currentTarget?: EventTarget;
  #defaultPrevented: boolean = false;
  #eventPhase: EventPhase = EventPhase.NONE;
  #isTrusted: boolean = false;
  #target?: EventTarget;
  #timeStamp: number = 0; // TODO: update to time (ms) since epoch
  #type: DOMString;

  get bubbles(): boolean { return this.#bubbles }
  get cancelable(): boolean { return this.#cancelable }
  get composed(): boolean { return this.#composed }
  get currentTarget(): EventTarget | undefined { return this.#currentTarget }
  get defaultPrevented(): boolean { return this.#defaultPrevented }
  get eventPhase(): number { return this.#eventPhase }
  get isTrusted(): boolean { return this.#isTrusted }
  get target(): EventTarget | undefined { return this.#target }
  get timeStamp(): number { return this.#timeStamp }
  get type(): DOMString { return this.#type }

  _setCurrentTarget(newTarget: EventTarget): void {
    this.#currentTarget = newTarget;
  }
  _setTarget(newTarget: EventTarget): void {
    this.#target = newTarget;
  }

  composedPath(): EventTarget[] { return [] }
  preventDefault() {}
  stopImmediatePropagation() {}
  stopPropagation() {}
}

interface EventInit {
  bubbles?: boolean,
  cancelable?: boolean,
  composed?: boolean,
}

const Event: EventConstructor = EventImpl;
export { Event };
